# CamIO Explorer launcher
# lets users choose a camera input and an output folder (produced by the Creator) before running the application
# -- this means the app has to be launched again if the user wants to try out a different camera or output folder

import argparse
from pathlib import Path

import pyglet

from explorer.camio_explorer import ExplorerApp

TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
DEFAULT_OUTPUT = TEMPLATES_DIR / "shapes"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="CamIO Explorer launcher")
    parser.add_argument(
        "--template",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to the template output folder generated by the Creator app.",
    )
    parser.add_argument(
        "--camera",
        type=int,
        default=0,
        help="Index of the camera input device to use.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    output_path = args.template
    if not output_path.exists():
        raise FileNotFoundError(f"Template output folder not found: {output_path}")

    app = ExplorerApp(args.camera, str(output_path.resolve()))
    pyglet.app.run()


if __name__ == "__main__":
    main()
